# Generated by Django 3.2.5 on 2021-07-15 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_raintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='raintable',
            name='county_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
