# Generated by Django 3.2.5 on 2021-07-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_raintable_county_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd_date', models.DateField()),
                ('rd_minimum', models.FloatField()),
                ('rd_maximum', models.FloatField()),
                ('rd_range', models.FloatField()),
                ('rd_mean', models.FloatField()),
                ('rd_std', models.FloatField()),
                ('rainTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.raintable')),
            ],
        ),
    ]
